source "https://rubygems.org"
ruby '~> 2.6.0'

gem "rake"
gem "ruboty"
gem "ruboty-alias"
gem "ruboty-replace"
gem "ruboty-cron"
gem "ruboty-google_image"
gem "ruboty-redis"
gem "ruboty-slack_rtm"
gem "ruboty-ume"
gem "ruboty-weather"
gem "ruboty-echo"
gem "ruboty-echo_to"
gem "ruboty-ruby"
gem "ruboty-talk"
gem "ruboty-github"
gem "ruboty-bundler"
gem "ruboty-eto"
gem "ruboty-irasutoya", :github => "june29/ruboty-irasutoya"

